const creators=[
{name:'Ananya Mehta',handle:'@ananyastyle',niche:'Fashion • Lifestyle',followers:'148K',country:'India',city:'Mumbai',eng:'6.0%',avgViews:'82K',auth:97,match:98,sponsored:true,price:35000,img:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85',cover:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=85',bio:'Fashion and lifestyle creator sharing modern Indian style, beauty routines and travel stories.',email:'ananya@collabai.demo',phone:'+91 98765 43210'},
{name:'Rohan Verma',handle:'@rohanbuilds',niche:'Technology',followers:'684K',country:'India',city:'Bengaluru',eng:'5.7%',avgViews:'310K',auth:95,match:94,sponsored:false,price:75000,img:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85',cover:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=85',bio:'Tech reviewer creating clear videos about smartphones, AI tools and consumer gadgets.',email:'rohan@collabai.demo',phone:'+91 98111 22334'},
{name:'Sofia Khan',handle:'@sofiafit',niche:'Fitness • Wellness',followers:'46K',country:'India',city:'Delhi',eng:'5.2%',avgViews:'29K',auth:96,match:91,sponsored:true,price:22000,img:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=85',cover:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1600&q=85',bio:'Certified fitness coach focused on workouts, nutrition and sustainable wellness.',email:'sofia@collabai.demo',phone:'+91 98989 45678'},
{name:'Kabir Singh',handle:'@kabirplays',niche:'Gaming',followers:'820K',country:'India',city:'Pune',eng:'7.1%',avgViews:'440K',auth:92,match:93,sponsored:false,price:90000,img:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85',cover:'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=85',bio:'Gaming entertainer creating livestreams, reviews and brand integrations.',email:'kabir@collabai.demo',phone:'+91 99880 77889'}];
const creatorServiceTemplates=[
 [
  {platform:'Instagram',type:'Reel',title:'Instagram Reel',description:'30–60 second branded reel with concept, filming, editing and caption.',price:35000,deliveryDays:7,revisions:1,icon:'▶'},
  {platform:'Instagram',type:'Story',title:'Instagram Story Set',description:'3 story frames with link, tag and call-to-action.',price:12000,deliveryDays:3,revisions:1,icon:'◉'},
  {platform:'Instagram',type:'Post',title:'Instagram Feed Post',description:'One premium feed photo or carousel with branded caption.',price:22000,deliveryDays:5,revisions:1,icon:'▦'},
  {platform:'YouTube',type:'Short',title:'YouTube Short',description:'Vertical short-form branded video up to 60 seconds.',price:30000,deliveryDays:7,revisions:1,icon:'▷'},
  {platform:'YouTube',type:'Video',title:'YouTube Integration',description:'60–90 second integration inside a long-form video.',price:65000,deliveryDays:14,revisions:2,icon:'▶'},
  {platform:'Facebook',type:'Reel',title:'Facebook Reel',description:'Native vertical reel published on the creator Facebook profile/page.',price:24000,deliveryDays:7,revisions:1,icon:'f'},
  {platform:'TikTok',type:'Video',title:'TikTok Video',description:'Native TikTok concept, filming, edit, caption and brand mention.',price:32000,deliveryDays:7,revisions:1,icon:'♪'}
 ],
 [
  {platform:'YouTube',type:'Video',title:'Dedicated YouTube Review',description:'Detailed product review with testing, edit and disclosure.',price:120000,deliveryDays:18,revisions:2,icon:'▶'},
  {platform:'YouTube',type:'Short',title:'YouTube Short',description:'Fast vertical product demo or feature highlight.',price:48000,deliveryDays:8,revisions:1,icon:'▷'},
  {platform:'Instagram',type:'Reel',title:'Instagram Tech Reel',description:'Feature-led Instagram reel with high-retention editing.',price:55000,deliveryDays:9,revisions:1,icon:'▶'},
  {platform:'Instagram',type:'Story',title:'Instagram Story Set',description:'4 story frames including link sticker and CTA.',price:18000,deliveryDays:4,revisions:1,icon:'◉'},
  {platform:'Facebook',type:'Video',title:'Facebook Video',description:'Native product explanation video for Facebook audience.',price:42000,deliveryDays:10,revisions:1,icon:'f'},
  {platform:'LinkedIn',type:'Post',title:'LinkedIn Sponsored Post',description:'Professional written post with product positioning and disclosure.',price:28000,deliveryDays:5,revisions:1,icon:'in'}
 ],
 [
  {platform:'Instagram',type:'Reel',title:'Workout Reel',description:'Exercise or wellness reel with product naturally integrated.',price:22000,deliveryDays:6,revisions:1,icon:'▶'},
  {platform:'Instagram',type:'Story',title:'Story Challenge Set',description:'5 interactive story frames with poll, link and CTA.',price:10000,deliveryDays:3,revisions:1,icon:'◉'},
  {platform:'Instagram',type:'Post',title:'Fitness Feed Post',description:'One feed post or carousel with caption and product tags.',price:15000,deliveryDays:5,revisions:1,icon:'▦'},
  {platform:'YouTube',type:'Short',title:'Fitness YouTube Short',description:'Vertical workout, recipe or wellness tip with brand mention.',price:20000,deliveryDays:7,revisions:1,icon:'▷'},
  {platform:'TikTok',type:'Video',title:'TikTok Fitness Video',description:'Trend-aware fitness video with native brand integration.',price:21000,deliveryDays:6,revisions:1,icon:'♪'}
 ],
 [
  {platform:'YouTube',type:'Video',title:'Gaming Integration',description:'Integrated brand segment in a gameplay or review video.',price:150000,deliveryDays:14,revisions:2,icon:'▶'},
  {platform:'YouTube',type:'Short',title:'Gaming Short',description:'Fast highlight, reaction or product feature short.',price:60000,deliveryDays:8,revisions:1,icon:'▷'},
  {platform:'Instagram',type:'Reel',title:'Gaming Reel',description:'Vertical gaming reel with branded hook and CTA.',price:65000,deliveryDays:8,revisions:1,icon:'▶'},
  {platform:'Twitch',type:'Live',title:'Sponsored Livestream',description:'60-minute sponsored livestream segment with chat callouts.',price:180000,deliveryDays:12,revisions:0,icon:'◈'},
  {platform:'Facebook',type:'Live',title:'Facebook Live',description:'30-minute live product feature and audience Q&A.',price:95000,deliveryDays:10,revisions:0,icon:'f'}
 ]
];
creators.forEach((creator,index)=>creator.services=creatorServiceTemplates[index]||creatorServiceTemplates[0]);
const brands=[
{name:'GlowNaturals',industry:'Beauty',campaign:'Summer Skin Launch',budget:'₹40K–₹1.2L',trust:98,match:96,sponsored:true,location:'Mumbai, India',logo:'GN',desc:'Clean beauty brand seeking skincare and lifestyle creators.',deliverables:'2 Reels + 3 Stories'},
{name:'NovaTech',industry:'Technology',campaign:'Smartphone Launch 2026',budget:'₹80K–₹2.5L',trust:96,match:94,sponsored:false,location:'Bengaluru, India',logo:'NT',desc:'Consumer electronics brand looking for tech reviewers.',deliverables:'1 YouTube Review + 2 Shorts'},
{name:'FitFuel',industry:'Fitness',campaign:'30 Day Wellness Challenge',budget:'₹25K–₹75K',trust:93,match:91,sponsored:true,location:'Delhi, India',logo:'FF',desc:'Nutrition and active lifestyle company seeking fitness voices.',deliverables:'3 Reels + Usage Rights'},
{name:'WanderNest',industry:'Travel',campaign:'Weekend Escape Series',budget:'₹50K–₹1.5L',trust:94,match:89,sponsored:false,location:'Goa, India',logo:'WN',desc:'Boutique travel stays partnering with travel storytellers.',deliverables:'2 Reels + Photo Set'}];
const plans=[{name:'Free',price:'₹0',features:['3 daily requests','Basic AI search','Standard profile']},{name:'Creator Pro',price:'₹799',features:['Sponsored creator profile','Priority brand matching','Advanced analytics']},{name:'Brand Pro',price:'₹1,499',popular:true,features:['Unlock full creator profiles','30 daily requests','Shortlist and payments']},{name:'Business',price:'₹4,999',features:['100 daily requests','Team access','API and account manager']}];
const unlocked=new Set(JSON.parse(localStorage.getItem('collabaiUnlockedCreators')||'[]'));let selectedCreator=0,selectedBrand=0,userRole=localStorage.getItem('collabaiRole')||'brand';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function route(){let h=(location.hash||'#home').slice(1);qa('.page').forEach(p=>p.classList.toggle('active',p.id===h));q('#publicHeader').style.display=['home','pricing','about','terms','privacy','refund','complaint','appeal'].includes(h)?'flex':'none';window.scrollTo(0,0)}addEventListener('hashchange',route);route();
function toast(m){let t=q('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showModal(h){q('#modalContent').innerHTML=h;q('#modal').classList.add('show')}function closeModal(){q('#modal').classList.remove('show')}q('#modalClose').onclick=closeModal;q('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
const brandNav=`<a class="side-brand" href="#home"><span class="brand-dot">C</span>CollabAI</a><div class="role-badge">Brand account</div><nav><a href="#dashboard">⌂ Dashboard</a><a href="#find-creators">⌕ Find Creators</a><a href="#requests">▧ Requests</a><a href="#payments">🛒 Cart & Checkout <span id="cartNavCount"></span></a><a href="#messages">✉ Messages</a><a href="#pricing">♛ Subscription</a><a href="#find-brands">⇄ Switch to Creator View</a></nav>`;
const creatorNav=`<a class="side-brand" href="#home"><span class="brand-dot">C</span>CollabAI</a><div class="role-badge creator-role">Creator account</div><nav><a href="#creator-dashboard">⌂ Dashboard</a><a href="#social-connect">◎ Connect Social Profiles</a><a href="#find-brands">⌕ Find Brands</a><a href="#requests">▧ Pitches</a><a href="#messages">✉ Messages</a><a href="#pricing">♛ Sponsored Profile</a><a href="#find-creators">⇄ Switch to Brand View</a></nav>`;
['brandSide','profileSide','dashSide','paySide'].forEach(id=>q('#'+id).innerHTML=brandNav);['creatorSide','brandProfileSide','creatorDashSide','socialSide'].forEach(id=>q('#'+id).innerHTML=creatorNav);q('#requestSide').innerHTML=brandNav;q('#messageSide').innerHTML=brandNav;
function renderCreators(list=creators){q('#creatorGrid').innerHTML=list.map((c,i)=>`<article class="creator-card ${c.sponsored?'sponsored-card':''}">${c.sponsored?'<span class="sponsored">Sponsored</span>':''}<div class="creator-photo" style="background-image:url('${c.img}')"></div><span class="match-pill">${c.match}% AI match</span><h3>${unlocked.has(i)?c.name:'Creator Profile'}</h3><p>${c.niche}</p><div class="score-row"><span>Authenticity</span><b>${c.auth}%</b></div><div class="scorebar"><i style="width:${c.auth}%"></i></div><div class="creator-meta"><span>${unlocked.has(i)?c.followers:'10K–1M'} followers</span><span>${c.country}</span></div><div class="creator-actions"><button class="btn primary" onclick="openProfile(${i})">${unlocked.has(i)?'View Profile':'View Locked Profile'}</button><button class="btn" onclick="sendCreatorRequest(${i})">Send Request</button></div></article>`).join('')}
function renderBrands(list=brands){q('#brandGrid').innerHTML=list.map((b,i)=>`<article class="brand-card ${b.sponsored?'sponsored-card':''}">${b.sponsored?'<span class="sponsored">Sponsored</span>':''}<div class="brand-logo">${b.logo}</div><div><span class="verified">✓ Verified Brand</span><h3>${b.name}</h3><p>${b.industry} · ${b.location}</p></div><div class="brand-campaign"><b>${b.campaign}</b><span>${b.deliverables}</span></div><div class="score-row"><span>Brand Trust</span><b>${b.trust}%</b></div><div class="score-row"><span>Creator Match</span><b>${b.match}%</b></div><strong class="budget">${b.budget}</strong><div class="creator-actions"><button class="btn" onclick="openBrand(${i})">View Brand</button><button class="btn primary" onclick="sendBrandPitch(${i})">Send Pitch</button></div></article>`).join('')}
renderCreators();renderBrands();
q('#creatorSearchBtn').onclick=()=>{let s=q('#creatorSearch').value.toLowerCase(),cat=q('#creatorCategory').value,af=q('#authFilter').value;let min=af==='95%+'?95:af==='90%+'?90:0;let r=creators.filter(c=>(!s||(`${c.name} ${c.niche} ${c.city}`).toLowerCase().includes(s))&&(cat==='All Categories'||c.niche.includes(cat))&&c.auth>=min).sort((a,b)=>b.match-a.match);renderCreators(r);toast(`AI ranked ${r.length} authentic creators`)};
q('#brandSearchBtn').onclick=()=>{let s=q('#brandSearch').value.toLowerCase(),cat=q('#brandCategory').value;let r=brands.filter(b=>(!s||(`${b.name} ${b.industry} ${b.campaign}`).toLowerCase().includes(s))&&(cat==='All Industries'||b.industry===cat)).sort((a,b)=>b.match-a.match);renderBrands(r);toast(`AI found ${r.length} matching brands`)};
window.openProfile=i=>{selectedCreator=i;renderProfile();location.hash='#creator-profile'};window.openBrand=i=>{selectedBrand=i;renderBrandProfile();location.hash='#brand-profile'};
function renderProfile(){
 const c=creators[selectedCreator];
 const el=q('#fullCreatorProfile');
 if(!el)return;
 if(!unlocked.has(selectedCreator)){
  el.innerHTML=`<article class="locked-profile classic-profile-lock">
   <div class="cover" style="background-image:linear-gradient(#1118,#1118),url('${c.cover}')"></div>
   <div class="profile-avatar blurred" style="background-image:url('${c.img}')"></div>
   <div class="lock-content"><div class="lock-icon">🔒</div><h2>This Creator's Profile is Locked</h2><p>Unlock this profile to view the creator’s identity, complete audience insights, authenticity score, contact details, portfolio and collaboration pricing.</p><button class="btn primary large" onclick="unlockCreator()">Unlock Profile 🔓</button></div>
   <div class="locked-metrics"><div>🔒<b>Followers</b></div><div>🔒<b>Engagement Rate</b></div><div>🔒<b>Authenticity</b></div><div>🔒<b>Pricing</b></div></div>
  </article>
  <div class="profile-bottom"><section class="panel"><h3>About Creator</h3><div class="skeleton"></div><div class="skeleton med"></div><div class="skeleton small"></div></section><aside class="why"><h3>Why profiles are hidden?</h3><p>◉ Protects creator privacy</p><p>◉ Ensures serious collaborations</p><p>◉ Reduces unwanted messages</p></aside></div>`;
  return;
 }
 el.innerHTML=`<article class="full-profile-card classic-full-profile">
   <div class="full-cover" style="background-image:linear-gradient(90deg,rgba(17,24,39,.45),rgba(17,24,39,.1)),url('${c.cover}')"></div>
   <div class="profile-main"><img class="full-avatar" src="${c.img}" alt="${c.name}"><div class="identity"><div class="verified">✓ Verified Creator</div><h1>${c.name}</h1><p>${c.handle} · ${c.niche}</p><span>📍 ${c.city}, ${c.country}</span></div><div class="profile-cta"><button class="btn white" onclick="toast('Profile saved')">☆ Save</button><button class="btn primary" onclick="sendCreatorRequest(${selectedCreator})">Send Collaboration Request</button></div></div>
   <div class="profile-metrics"><div><strong>${c.followers}</strong><span>Followers</span></div><div><strong>${c.eng}</strong><span>Engagement Rate</span></div><div><strong>${c.avgViews}</strong><span>Average Views</span></div><div><strong>${c.auth}%</strong><span>Authenticity</span></div><div><strong>${c.match}%</strong><span>AI Match Score</span></div></div>
  </article>
  <div class="full-profile-grid classic-profile-grid"><div class="profile-column">
   <section class="panel profile-section"><h3>About ${c.name.split(' ')[0]}</h3><p>${c.bio}</p><div class="tag-list"><span>${c.niche.split(' • ')[0]}</span><span>Sponsored Content</span><span>Brand Collaborations</span></div></section>
   <section class="panel profile-section"><h3>Audience Insights</h3><div class="insight-grid"><div><b>Age group</b><strong>18–34</strong><small>Primary audience</small></div><div><b>Gender split</b><strong>68% Women</strong><small>32% Men</small></div><div><b>Top location</b><strong>${c.country}</strong><small>${c.city} leads</small></div><div><b>Authenticity</b><strong>${c.auth}%</strong><small>AI checked audience</small></div></div></section>
   <section class="panel profile-section services-section"><div class="section-row compact"><div><h3>Book Content Deliverables</h3><p class="muted">Choose Instagram, YouTube and other social deliverables. Add multiple items to one order.</p></div><span class="ai-chip">Secure marketplace checkout</span></div><div class="platform-tabs">${[...new Set(c.services.map(x=>x.platform))].map((p,n)=>`<button class="${n===0?'active':''}" onclick="filterServices(this,'${p}')">${p}</button>`).join('')}<button onclick="filterServices(this,'all')">All</button></div><div class="service-grid">${c.services.map((service,serviceIndex)=>`<article class="service-card" data-platform="${service.platform}"><div class="service-icon">${service.icon}</div><div class="service-copy"><span>${service.platform} · ${service.type}</span><h4>${service.title}</h4><p>${service.description}</p><div class="service-meta"><small>Delivery: ${service.deliveryDays} days</small><small>${service.revisions} revision${service.revisions===1?'':'s'}</small></div></div><div class="service-buy"><strong>₹${service.price.toLocaleString('en-IN')}</strong><label>Qty <select id="qty-${selectedCreator}-${serviceIndex}"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><button class="btn primary small" onclick="addServiceToCart(${selectedCreator},${serviceIndex})">Add to Cart</button></div></article>`).join('')}</div></section>
   <section class="panel profile-section"><h3>Recent Work</h3><div class="portfolio-grid"><div style="background-image:url('${c.cover}')"></div><div style="background-image:url('${c.img}')"></div><div style="background-image:url('${c.cover}')"></div></div></section>
  </div><aside class="profile-column">
   <section class="panel profile-section"><h3>AI Authenticity Review</h3><p class="safety">✓ Consistent engagement pattern</p><p class="safety">✓ Low fake-follower probability</p><p class="safety">✓ Brand-safe content history</p><div class="auth-score-box"><strong>${c.auth}%</strong><span>Authenticity score</span></div></section>
   <section class="panel profile-section contact-card protected-contact"><h3>Protected Contact</h3><div class="privacy-lock"><span>🔒</span><div><b>Email and phone are hidden</b><small>Contact details are shared only after the creator accepts the request or an order is funded.</small></div></div><p><b>Starting from</b><span>₹${Math.min(...c.services.map(x=>x.price)).toLocaleString('en-IN')}</span></p><p><b>Response time</b><span>Usually within 4 hours</span></p><span class="protected-badge">✓ Protected by CollabAI</span><button class="btn" onclick="shortlist(${selectedCreator})">Shortlist Creator</button><button class="btn primary" onclick="location.hash='#payments'">View Cart (<span class="cart-count">0</span>)</button></section>
   <section class="panel profile-section"><h3>Brand Safety</h3><p class="safety">✓ No suspicious audience activity</p><p class="safety">✓ Content suitable for brands</p><p class="safety">✓ Identity verified by CollabAI</p></section>
  </aside></div>`;
}
function renderBrandProfile(){let b=brands[selectedBrand];q('#fullBrandProfile').innerHTML=`<article class="brand-profile-card"><div class="brand-logo huge">${b.logo}</div><div><span class="verified">✓ Identity & business verified</span><h1>${b.name}</h1><p>${b.industry} · ${b.location}</p></div><div class="profile-cta"><button class="btn primary" onclick="sendBrandPitch(${selectedBrand})">Send Collaboration Pitch</button></div></article><div class="full-profile-grid"><section class="panel profile-section"><h3>About Brand</h3><p>${b.desc}</p><h3>Active Campaign</h3><h2>${b.campaign}</h2><p>${b.deliverables}</p><h3>AI Brand Safety</h3><p class="safety">✓ Business identity verified</p><p class="safety">✓ Payment history checked</p><p class="safety">✓ No unresolved creator complaints</p></section><aside class="panel profile-section"><h3>Campaign Budget</h3><div class="big-price">${b.budget}</div><div class="profile-metrics mini"><div><strong>${b.trust}%</strong><span>Trust score</span></div><div><strong>${b.match}%</strong><span>Your match</span></div></div><button class="btn primary" onclick="sendBrandPitch(${selectedBrand})">Pitch This Brand</button></aside></div>`}
const requestData=[];function sendCreatorRequest(i){let c=creators[i];showModal(`<div class="auth-head"><span class="auth-icon">✦</span><h2>Send Request to ${c.name}</h2><p>AI match ${c.match}% · Authenticity ${c.auth}%</p></div><form id="reqForm"><label>Campaign</label><select><option>Summer Glow</option><option>Product Launch</option></select><label>Message</label><textarea rows="5" required placeholder="Explain the campaign and deliverables..."></textarea><button class="btn primary wide">Send Request</button></form>`);q('#reqForm').onsubmit=e=>{e.preventDefault();requestData.push([c.name,'Brand → Creator','Pending']);renderRequests();closeModal();toast('Collaboration request sent')}}
function sendBrandPitch(i){let b=brands[i];showModal(`<div class="auth-head"><span class="auth-icon">✦</span><h2>Pitch ${b.name}</h2><p>${b.match}% creator-brand match</p></div><form id="pitchForm"><label>Your pitch</label><textarea rows="5" required placeholder="Why are you a strong fit for this campaign?"></textarea><label>Your quote</label><input placeholder="₹ Amount" required><button class="btn primary wide">Send Pitch</button></form>`);q('#pitchForm').onsubmit=e=>{e.preventDefault();requestData.push([b.name,'Creator → Brand','Pending']);renderRequests();closeModal();toast('Pitch sent to brand')}}
function renderRequests(){q('#requestList').innerHTML=`<div class="row header"><span>Recipient</span><span>Direction</span><span>Status</span><span>Action</span></div>`+(requestData.length?requestData.map(r=>`<div class="row"><b>${r[0]}</b><span>${r[1]}</span><i class="status">${r[2]}</i><button class="btn small">View</button></div>`).join(''):`<div class="empty">No requests yet. Search creators or brands to send one.</div>`)}renderRequests();
let shortlisted=[0,2];window.shortlist=i=>{if(!shortlisted.includes(i))shortlisted.push(i);renderShortlist();renderPayments();toast('Creator shortlisted')};function renderShortlist(){q('#shortlistTable').innerHTML=shortlisted.map(i=>{let c=creators[i];return `<div class="short-row"><img src="${c.img}"><div><b>${c.name}</b><span>${c.niche}</span></div><strong>₹${c.price.toLocaleString('en-IN')}</strong><a class="btn primary small" href="#payments" onclick="selectPayment(${i})">Pay</a></div>`}).join('')}renderShortlist();
const cart=JSON.parse(localStorage.getItem('collabaiCart')||'[]');
function saveCart(){localStorage.setItem('collabaiCart',JSON.stringify(cart));updateCartCounts();renderPayments()}
function updateCartCounts(){const count=cart.reduce((n,x)=>n+x.quantity,0);qa('.cart-count').forEach(x=>x.textContent=count);const nav=q('#cartNavCount');if(nav)nav.textContent=count?`(${count})`:''}
window.filterServices=(button,platform)=>{button.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));button.classList.add('active');button.closest('.services-section').querySelectorAll('.service-card').forEach(card=>card.style.display=platform==='all'||card.dataset.platform===platform?'grid':'none')};
window.addServiceToCart=(creatorIndex,serviceIndex)=>{const c=creators[creatorIndex],service=c.services[serviceIndex],quantity=Number(q(`#qty-${creatorIndex}-${serviceIndex}`)?.value||1);const key=`${creatorIndex}:${serviceIndex}`;const existing=cart.find(x=>x.key===key);if(existing)existing.quantity+=quantity;else cart.push({key,creatorIndex,serviceIndex,quantity,creatorName:c.name,creatorImage:c.img,...service});saveCart();toast(`${service.title} added to cart`)};
window.removeCartItem=key=>{const i=cart.findIndex(x=>x.key===key);if(i>=0)cart.splice(i,1);saveCart();toast('Item removed')};
window.changeCartQty=(key,value)=>{const item=cart.find(x=>x.key===key);if(item){item.quantity=Math.max(1,Math.min(10,Number(value)||1));saveCart()}};
function cartTotals(){const subtotal=cart.reduce((n,x)=>n+x.price*x.quantity,0),platformFee=Math.round(subtotal*.05),gst=Math.round(platformFee*.18);return{subtotal,platformFee,gst,total:subtotal+platformFee+gst}}
function renderPayments(){
 const list=q('#paymentCreators'),summary=q('#paymentSummary');if(!list||!summary)return;
 if(!cart.length){list.innerHTML='<div class="empty-cart"><div>🛒</div><h3>Your cart is empty</h3><p>Open an unlocked creator profile and add Reels, Stories, Posts, Shorts, Videos or other social deliverables.</p><a class="btn primary" href="#find-creators">Browse Creators</a></div>';summary.innerHTML='<div class="checkout-empty"><span>🔒</span><h3>Secure checkout</h3><p>Your order summary will appear here after adding a creator service.</p></div>';updateCartCounts();updateDynamicDashboards();return}
 const grouped={};cart.forEach(x=>(grouped[x.creatorName]??=[]).push(x));
 list.innerHTML=Object.entries(grouped).map(([name,items])=>`<section class="creator-cart-group"><div class="creator-cart-head"><img src="${items[0].creatorImage}"><div><b>${name}</b><span>${items.length} selected service${items.length===1?'':'s'}</span></div><strong>₹${items.reduce((n,x)=>n+x.price*x.quantity,0).toLocaleString('en-IN')}</strong></div>${items.map(x=>`<div class="cart-row"><div class="platform-service-icon">${x.icon||'✦'}</div><div class="cart-item-info"><span>${x.platform} · ${x.type}</span><b>${x.title}</b><small>Delivery in ${x.deliveryDays} days · ${x.revisions} revision${x.revisions===1?'':'s'}</small></div><label>Quantity<select onchange="changeCartQty('${x.key}',this.value)">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option ${n===x.quantity?'selected':''}>${n}</option>`).join('')}</select></label><strong>₹${(x.price*x.quantity).toLocaleString('en-IN')}</strong><button class="remove-cart" onclick="removeCartItem('${x.key}')" aria-label="Remove">×</button></div>`).join('')}</section>`).join('');
 const t=cartTotals(),creatorNames=Object.keys(grouped);
 summary.innerHTML=`<div class="checkout-steps"><span class="active">1 Review</span><span class="active">2 Details</span><span>3 Payment</span></div><div class="checkout-title"><div><h3>Order Summary</h3><p>${creatorNames.length} creator${creatorNames.length===1?'':'s'} · ${cart.reduce((n,x)=>n+x.quantity,0)} deliverable${cart.reduce((n,x)=>n+x.quantity,0)===1?'':'s'}</p></div><span class="secure">🔒 Protected</span></div><div class="order-creators">${creatorNames.map(name=>`<span>${name}</span>`).join('')}</div><div class="bill"><p><span>Services subtotal</span><b>₹${t.subtotal.toLocaleString('en-IN')}</b></p><p><span>CollabAI protection fee (5%)</span><b>₹${t.platformFee.toLocaleString('en-IN')}</b></p><p><span>GST on protection fee</span><b>₹${t.gst.toLocaleString('en-IN')}</b></p><p class="total"><span>Total payable</span><b>₹${t.total.toLocaleString('en-IN')}</b></p></div><form id="payForm" class="organised-checkout"><fieldset><legend>Campaign details</legend><label>Campaign / brief</label><textarea name="brief" rows="3" required placeholder="Describe the product, key message and expected content"></textarea><div class="checkout-two"><label>Completion date<input name="deadline" type="date" required></label><label>Usage rights<select name="rights"><option>Organic social use only</option><option>30-day paid advertising rights</option><option>90-day paid advertising rights</option><option>12-month digital usage rights</option></select></label></div></fieldset><fieldset><legend>Billing & payment</legend><label>Billing email<input name="email" type="email" required placeholder="billing@brand.com"></label><div class="payment-methods"><label><input type="radio" name="method" value="UPI" checked><span>UPI<small>Google Pay, PhonePe, Paytm</small></span></label><label><input type="radio" name="method" value="Card"><span>Card<small>Credit or debit card</small></span></label><label><input type="radio" name="method" value="Net Banking"><span>Net Banking<small>All major banks</small></span></label></div></fieldset><label class="terms-check"><input type="checkbox" required> I agree to the deliverables, cancellation, refund and platform protection terms.</label><button class="btn primary wide checkout-pay-btn">Pay ₹${t.total.toLocaleString('en-IN')} Securely</button><p class="checkout-note">Creator contact remains protected until the order is funded or the collaboration request is accepted.</p></form>`;
 q('#payForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),orderId='ORD'+Date.now().toString().slice(-8);const order={id:orderId,items:[...cart],...Object.fromEntries(fd),totals:t,creators:creatorNames,status:'Funded',createdAt:new Date().toISOString()};localStorage.setItem('collabaiLastOrder',JSON.stringify(order));const history=JSON.parse(localStorage.getItem('collabaiOrders')||'[]');history.unshift(order);localStorage.setItem('collabaiOrders',JSON.stringify(history));cart.splice(0);saveCart();updateDynamicDashboards();showModal(`<div class="success-pay"><div>✓</div><h2>Payment Successful</h2><p>Order <b>${orderId}</b> is funded for ${creatorNames.join(', ')}. Contact details stay protected until acceptance.</p><div class="order-success-total">₹${t.total.toLocaleString('en-IN')}</div><button class="btn primary" onclick="closeModal();location.hash='#dashboard'">View Dashboard</button></div>`)};
 updateCartCounts();updateDynamicDashboards();
}
function updateDynamicDashboards(){
 const cartTotal=cartTotals().total;
 const orders=JSON.parse(localStorage.getItem('collabaiOrders')||'[]');
 const paid=orders.reduce((n,o)=>n+(o.totals?.total||0),0);
 const pendingCreator=orders.reduce((n,o)=>n+(o.totals?.subtotal||0),0);
 const set=(id,val)=>{const el=q('#'+id);if(el)el.textContent=val};
 set('brandShortlistedCount',shortlisted.length);set('brandCartDue',`₹${cartTotal.toLocaleString('en-IN')}`);set('brandTotalSpent',`₹${paid.toLocaleString('en-IN')}`);set('creatorPendingEarnings',`₹${pendingCreator.toLocaleString('en-IN')}`);set('creatorCompletedOrders',orders.length);
 const box=q('#creatorPaymentBreakdown');if(box)box.innerHTML=orders.length?orders.slice(0,5).map(o=>`<div class="payment-activity"><div><b>${o.id}</b><span>${(o.items||[]).map(i=>i.title).slice(0,2).join(', ')}</span></div><strong>₹${(o.totals?.subtotal||0).toLocaleString('en-IN')}</strong><i>${o.status||'Funded'}</i></div>`).join(''):'<div class="empty">No funded creator orders yet.</div>';
 const brandBox=q('#brandPaymentBreakdown');if(brandBox)brandBox.innerHTML=cart.length?Object.values(cart.reduce((a,x)=>{(a[x.creatorName]??={name:x.creatorName,img:x.creatorImage,total:0,count:0});a[x.creatorName].total+=x.price*x.quantity;a[x.creatorName].count+=x.quantity;return a},{})).map(x=>`<div class="payment-activity"><img src="${x.img}"><div><b>${x.name}</b><span>${x.count} deliverable${x.count===1?'':'s'} in cart</span></div><strong>₹${x.total.toLocaleString('en-IN')}</strong><a class="btn primary small" href="#payments">Pay</a></div>`).join(''):'<div class="empty">Add creator services to see creator-wise payable amounts.</div>';
}

renderPayments();updateCartCounts();updateDynamicDashboards();
window.selectPayment=i=>{const c=creators[i],serviceIndex=0;addServiceToCart(i,serviceIndex);location.hash='#payments'};
q('#plans').innerHTML=plans.map(p=>`<div class="plan ${p.popular?'popular':''}">${p.popular?'<span class="badge">Most Popular</span>':''}<h3>${p.name}</h3><div class="price">${p.price}<small>/month</small></div><ul>${p.features.map(f=>`<li>✓ ${f}</li>`).join('')}</ul><button class="btn ${p.popular?'primary':''}" onclick="choosePlan('${p.name}')">Choose Plan</button></div>`).join('');window.choosePlan=n=>showModal(`<div class="auth-head"><span class="auth-icon">♛</span><h2>${n} Checkout</h2><p>Demo subscription payment screen</p></div><form onsubmit="event.preventDefault();closeModal();toast('${n} activated')"><label>Name</label><input required><label>Email</label><input type="email" required><label>Card / UPI</label><input required placeholder="Payment details"><button class="btn primary wide">Subscribe</button></form>`);
function authModal(type){showModal(`<div class="auth-shell"><div class="auth-head"><span class="auth-icon">C</span><h2>${type==='login'?'Welcome back':'Create your account'}</h2><p>Choose how you want to use CollabAI.</p></div><div class="role-switch"><button class="active" data-role="brand">🏢 Brand</button><button data-role="creator">✦ Creator</button></div><form id="authForm">${type==='signup'?'<label>Full name / Company</label><input required>':''}<label>Email</label><input type="email" required><label>Password</label><input type="password" required><div class="auth-options"><label><input type="checkbox"> Remember me</label><a href="#">Forgot password?</a></div><button class="btn primary wide">${type==='login'?'Login':'Create Account'}</button><div class="divider"><span>or continue with</span></div><button type="button" class="social-login">G &nbsp; Continue with Google</button></form></div>`);let role='brand';qa('.role-switch button').forEach(b=>b.onclick=()=>{qa('.role-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');role=b.dataset.role});q('#authForm').onsubmit=e=>{e.preventDefault();userRole=role;localStorage.setItem('collabaiRole',role);closeModal();toast(`${role==='brand'?'Brand':'Creator'} account ready`);location.hash=role==='brand'?'#dashboard':'#creator-dashboard'}}
qa('[data-action="login"]').forEach(b=>b.onclick=()=>authModal('login'));qa('[data-action="signup"]').forEach(b=>b.onclick=()=>authModal('signup'));


// Multi-social connection and import
const socialProviders = [
 {id:'instagram',name:'Instagram',icon:'◎',subtitle:'Professional Creator or Business',accent:'Instagram',demo:{provider:'instagram',username:'your_instagram_id',display_name:'Your Creator Name',bio_description:'Lifestyle creator • Reels • Brand collaborations',avatar_url:creators[0].img,follower_count:128450,following_count:614,video_count:286,engagement_rate:5.8,view_count:74500}},
 {id:'tiktok',name:'TikTok',icon:'♪',subtitle:'Login Kit + Display API',accent:'TikTok',demo:{provider:'tiktok',display_name:'Your TikTok Creator',bio_description:'Short videos • Lifestyle • Trends',avatar_url:creators[2].img,follower_count:246900,following_count:383,video_count:194,likes_count:3100000,engagement_rate:7.1,view_count:182000}},
 {id:'youtube',name:'YouTube',icon:'▶',subtitle:'YouTube Data API v3',accent:'YouTube',demo:{provider:'youtube',display_name:'Your YouTube Channel',bio_description:'Tech reviews, tutorials and creator stories',avatar_url:creators[1].img,follower_count:86400,video_count:142,view_count:12850000,engagement_rate:4.9}},
 {id:'facebook',name:'Facebook',icon:'f',subtitle:'Facebook Login + managed Page',accent:'Facebook',demo:{provider:'facebook',display_name:'Your Facebook Page',bio_description:'Creator page and community updates',avatar_url:creators[3].img,follower_count:93600,fan_count:91100,video_count:118,engagement_rate:4.3,view_count:58000,page:true}}
];
const socialData = JSON.parse(localStorage.getItem('collabaiSocialProfiles')||'{}');
function normalizeProfile(provider,p){
 return {provider,display_name:p.display_name||p.name||p.username||'Connected creator',username:p.username||'',bio_description:p.bio_description||p.biography||p.about||'',avatar_url:p.avatar_url||p.profile_picture_url||p.picture?.data?.url||creators[0].img,profile_deep_link:p.profile_deep_link||p.website||'',follower_count:Number(p.follower_count||p.followers_count||p.subscriber_count||0),following_count:Number(p.following_count||p.follows_count||0),video_count:Number(p.video_count||p.media_count||0),view_count:Number(p.view_count||p.avg_views||0),likes_count:Number(p.likes_count||0),engagement_rate:Number(p.engagement_rate||0),recent_media:p.recent_media||[],page:p.page,note:p.note};
}
function authenticity(p){
 const followers=Math.max(p.follower_count,1), recent=p.recent_media||[];
 const avgInteractions=recent.length?recent.reduce((n,x)=>n+Number(x.like_count||0)+Number(x.comments_count||0),0)/recent.length:0;
 const estimatedEngagement=p.engagement_rate||((avgInteractions/followers)*100)||(p.view_count?Math.min(12,p.view_count/followers*8):3.5);
 const engagementScore=Math.min(100,estimatedEngagement*14);
 const consistency=Math.min(100,p.video_count*1.8);
 const completeness=[p.display_name,p.bio_description,p.avatar_url,p.follower_count].filter(Boolean).length*25;
 const reach=p.view_count?Math.min(100,(p.view_count/followers)*120):65;
 return Math.max(35,Math.min(99,Math.round(engagementScore*.35+reach*.25+consistency*.20+completeness*.20)));
}
function saveSocial(){localStorage.setItem('collabaiSocialProfiles',JSON.stringify(socialData));renderProviders();renderUnified()}
function providerCard(x){const p=socialData[x.id],score=p?authenticity(p):null;return `<article class="panel provider-card ${p?'provider-connected':''}"><div class="provider-title"><span class="provider-icon ${x.id}">${x.icon}</span><div><h3>${x.name}</h3><p>${x.subtitle}</p></div>${p?'<span class="connected-pill">Connected</span>':''}</div>${p?`<div class="mini-social"><img src="${p.avatar_url}" alt=""><div><b>${p.display_name}</b><span>${p.follower_count.toLocaleString()} followers</span></div><strong>${score}%<small>AI score</small></strong></div>`:`<p class="muted">Securely import the profile and statistics allowed by ${x.name}.</p>`}<div class="provider-actions">${p?`<button class="btn primary" onclick="refreshSocial('${x.id}')">Refresh</button><button class="btn" onclick="disconnectSocial('${x.id}')">Disconnect</button>`:`<button class="btn primary" onclick="connectSocial('${x.id}')">Connect ${x.name}</button><button class="btn" onclick="demoSocial('${x.id}')">Try Demo</button>`}</div></article>`}
function renderProviders(){const el=q('#providerGrid');if(el)el.innerHTML=socialProviders.map(providerCard).join('')}
function renderUnified(){const el=q('#unifiedProfile');if(!el)return;const profiles=Object.values(socialData);if(!profiles.length){el.className='instagram-preview empty-preview';el.textContent='Connect or demo at least one platform to build your creator profile.';return}const total=profiles.reduce((n,p)=>n+p.follower_count,0),weighted=Math.round(profiles.reduce((n,p)=>n+authenticity(p),0)/profiles.length);el.className='instagram-preview';el.innerHTML=`<div class="ig-profile-head"><img src="${profiles[0].avatar_url}" alt=""><div><h3>${profiles[0].display_name}</h3><p>${profiles[0].bio_description||'Connected creator profile'}</p><div class="platform-tags">${profiles.map(p=>`<span>${p.provider}</span>`).join('')}</div></div><strong>${weighted}%<small>Combined score</small></strong></div><div class="ig-stats"><div><b>${total.toLocaleString()}</b><span>Total followers</span></div><div><b>${profiles.length}</b><span>Platforms</span></div><div><b>${profiles.reduce((n,p)=>n+p.video_count,0).toLocaleString()}</b><span>Published items</span></div><div><b>${Math.round(profiles.reduce((n,p)=>n+(p.engagement_rate||0),0)/profiles.length*10)/10||'AI' }%</b><span>Avg. engagement</span></div></div><div class="connected-list">${profiles.map(p=>`<div><span class="provider-icon ${p.provider}">${socialProviders.find(x=>x.id===p.provider)?.icon||'•'}</span><div><b>${p.display_name}</b><small>${p.follower_count.toLocaleString()} followers • ${authenticity(p)}% authenticity</small></div></div>`).join('')}</div>`}
window.connectSocial=async id=>{try{const r=await fetch(`/api/${id}/auth-url`),d=await r.json();if(!r.ok)throw new Error(d.error||`${id} setup incomplete`);location.href=d.url}catch(e){showModal(`<div class="auth-head"><span class="auth-icon">↗</span><h2>Developer setup required</h2><p>${e.message}</p></div><p>Add this platform's credentials to <b>.env</b>, configure its exact redirect URL, then restart the server.</p><button class="btn primary wide" onclick="closeModal()">Okay</button>`)}};
window.refreshSocial=async id=>{try{const r=await fetch(`/api/${id}/profile`),d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to refresh');socialData[id]=normalizeProfile(id,d);saveSocial();toast(`${socialProviders.find(x=>x.id===id).name} refreshed`)}catch(e){toast(e.message)}};
window.disconnectSocial=async id=>{try{await fetch(`/api/${id}/disconnect`,{method:'POST'})}catch(e){}delete socialData[id];saveSocial();toast(`${socialProviders.find(x=>x.id===id).name} disconnected`)};
window.demoSocial=id=>{const x=socialProviders.find(x=>x.id===id);socialData[id]=normalizeProfile(id,x.demo);saveSocial();toast(`${x.name} demo imported`)};
renderProviders();renderUnified();
const refreshAll=q('#refreshAllBtn');if(refreshAll)refreshAll.onclick=async()=>{for(const id of Object.keys(socialData)){try{const r=await fetch(`/api/${id}/profile`);if(r.ok)socialData[id]=normalizeProfile(id,await r.json())}catch(e){}}saveSocial();toast('Connected profiles refreshed')};
const params=new URLSearchParams(location.search);for(const x of socialProviders){if(params.get(x.id)==='connected'){history.replaceState({},'',location.pathname+'#social-connect');setTimeout(()=>refreshSocial(x.id),250)}if(params.get(`${x.id}_error`)){const msg=params.get(`${x.id}_error`);history.replaceState({},'',location.pathname+'#social-connect');setTimeout(()=>toast(msg),250)}}

// Production starter additions: campaigns, analytics, API-backed auth and support forms.
const campaignNav=`<a class="side-brand" href="#home"><span class="brand-dot">C</span>CollabAI</a><div class="role-badge">Brand account</div><nav><a href="#dashboard">⌂ Dashboard</a><a href="#campaigns">▣ Campaigns</a><a href="#find-creators">⌕ Find Creators</a><a href="#requests">▧ Requests</a><a href="#payments">🛒 Cart & Checkout <span id="cartNavCount"></span></a><a href="#messages">✉ Messages</a><a href="#analytics">◫ Analytics</a></nav>`;
if(q('#campaignSide'))q('#campaignSide').innerHTML=campaignNav;
if(q('#analyticsSide'))q('#analyticsSide').innerHTML=creatorNav;
if(q('#adminSide'))q('#adminSide').innerHTML=`<a class="side-brand" href="#home"><span class="brand-dot">C</span>CollabAI</a><div class="role-badge">Admin</div><nav><a href="#admin">⌂ Overview</a><a href="#campaigns">▣ Campaigns</a><a href="#payments">🛒 Cart & Checkout <span id="cartNavCount"></span></a><a href="#complaint">! Complaints</a><a href="#appeal">↺ Appeals</a></nav>`;
const demoCampaigns=[
 {title:'Summer Skin Launch',status:'Published',budget:'₹80,000',apps:42,due:'15 Sep'},
 {title:'AI Phone Review',status:'Shortlisting',budget:'₹1,50,000',apps:28,due:'28 Aug'},
 {title:'Wellness Challenge',status:'In progress',budget:'₹65,000',apps:12,due:'05 Sep'}
];
function renderCampaignBoard(){const el=q('#campaignBoard');if(!el)return;el.innerHTML=demoCampaigns.map(c=>`<article class="campaign-item"><div><span class="verified">${c.status}</span><h3>${c.title}</h3><p>${c.apps} creator applications • Due ${c.due}</p></div><strong>${c.budget}</strong><button class="btn">Manage</button></article>`).join('')}
renderCampaignBoard();
window.openCampaignBuilder=()=>{
 showModal(`<div class="auth-head"><span class="auth-icon">▣</span><h2>Create campaign</h2><p>Build a clear brief for AI creator matching.</p></div><form id="campaignForm"><label>Campaign title</label><input name="title" required><label>Category</label><select name="category"><option>Fashion</option><option>Technology</option><option>Fitness</option><option>Beauty</option></select><label>Budget (INR)</label><input name="budget" type="number" required><label>Deadline</label><input name="deadline" type="date"><label>Deliverables</label><textarea name="deliverables" placeholder="2 Reels, 3 Stories"></textarea><button class="btn primary wide">Save Draft</button></form>`);
 setTimeout(()=>{
  const f=q('#campaignForm');
  if(!f)return;
  f.onsubmit=async e=>{
   e.preventDefault();
   const fd=new FormData(f),payload=Object.fromEntries(fd);
   payload.deliverables=payload.deliverables.split(',').map(x=>x.trim()).filter(Boolean);
   try{
    const token=localStorage.getItem('collabaiToken');
    const r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});
    if(!r.ok)throw new Error((await r.json()).error);
    closeModal();toast('Campaign draft saved');
   }catch(err){
    closeModal();toast('Demo saved locally — login to save on server');
    demoCampaigns.unshift({title:payload.title,status:'Draft',budget:`₹${Number(payload.budget).toLocaleString('en-IN')}`,apps:0,due:payload.deadline||'TBD'});
    renderCampaignBoard();
   }
  };
 },50);
};

async function apiAuth(type,role,name,email,password){const endpoint=type==='login'?'/api/auth/login':'/api/auth/signup';const body=type==='login'?{email,password}:{name,email,password,role};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Authentication failed');localStorage.setItem('collabaiToken',d.token);localStorage.setItem('collabaiRole',d.user.role);return d;}
// Upgrade existing modal form to use server API while retaining demo-friendly fallback.
const originalAuthModal=authModal;
authModal=function(type){showModal(`<div class="auth-shell"><div class="auth-head"><span class="auth-icon">C</span><h2>${type==='login'?'Welcome back':'Create your account'}</h2><p>Secure role-based access for brands and creators.</p></div><div class="role-switch"><button class="active" data-role="brand">🏢 Brand</button><button data-role="creator">✦ Creator</button></div><form id="authForm">${type==='signup'?'<label>Full name / Company</label><input name="name" required>':''}<label>Email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" minlength="8" required><div class="auth-options"><label><input type="checkbox"> Remember me</label><a href="#">Forgot password?</a></div><button class="btn primary wide">${type==='login'?'Login':'Create Account'}</button><div class="divider"><span>or continue with</span></div><button type="button" class="social-login">G &nbsp; Continue with Google</button></form></div>`);let role='brand';qa('.role-switch button').forEach(b=>b.onclick=()=>{qa('.role-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');role=b.dataset.role});q('#authForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{const d=await apiAuth(type,role,fd.get('name')||'User',fd.get('email'),fd.get('password'));closeModal();toast(`${d.user.role==='brand'?'Brand':'Creator'} account ready`);location.hash=d.user.role==='brand'?'#dashboard':'#creator-dashboard';}catch(err){toast(err.message)}}}
qa('[data-action="login"]').forEach(b=>b.onclick=()=>authModal('login'));qa('[data-action="signup"]').forEach(b=>b.onclick=()=>authModal('signup'));


// ---------- Dynamic data layer ----------
const apiToken=()=>localStorage.getItem('collabaiToken');
const apiHeaders=()=>({'Content-Type':'application/json',...(apiToken()?{Authorization:`Bearer ${apiToken()}`}:{})});
function compactFollowers(n){n=Number(n||0);if(n>=1e6)return `${(n/1e6).toFixed(n%1e6?1:0)}M`;if(n>=1e3)return `${(n/1e3).toFixed(n%1e3?1:0)}K`;return String(n)}
function mapApiCreator(x){return {id:x.id,name:x.name,handle:x.handle,niche:x.niche,followers:compactFollowers(x.followers),followersRaw:x.followers,country:x.country,city:x.city,eng:`${x.engagement}%`,avgViews:compactFollowers(x.avgViews),auth:x.authenticity,match:x.match,sponsored:x.sponsored,price:x.price,img:x.image||'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=85',cover:x.cover||'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85',bio:x.bio,email:x.email,phone:x.phone,verified:x.verified};}
function mapApiBrand(x){return {id:x.id,name:x.name,industry:x.industry,campaign:x.campaign,budget:x.budget,trust:x.trust,match:x.match,sponsored:x.sponsored,location:x.location,logo:x.logo,desc:x.description,deliverables:x.deliverables,verified:x.verified,website:x.website};}
async function loadDynamicMarketplace(){
 try{
  const [cr,br]=await Promise.all([fetch('/api/discovery/creators'),fetch('/api/discovery/brands')]);
  if(cr.ok){const rows=(await cr.json()).map(mapApiCreator);if(rows.length){creators.splice(0,creators.length,...rows);renderCreators();}}
  if(br.ok){const rows=(await br.json()).map(mapApiBrand);if(rows.length){brands.splice(0,brands.length,...rows);renderBrands();}}
 }catch(e){console.warn('Dynamic API unavailable; using bundled demo data',e)}
}
loadDynamicMarketplace();

const originalSendCreatorRequest=window.sendCreatorRequest;
window.sendCreatorRequest=async i=>{
 const c=creators[i];
 if(!apiToken())return authModal('login');
 showModal(`<div class="auth-head"><span class="auth-icon">✦</span><h2>Send request to ${c.name}</h2><p>Include campaign details, deliverables and budget.</p></div><form id="dynamicRequestForm"><label>Message</label><textarea name="message" required placeholder="We would like to collaborate on..."></textarea><label>Offer amount (INR)</label><input name="amount" type="number" min="0" value="${c.price||0}"><button class="btn primary wide">Send Request</button></form>`);
 setTimeout(()=>{const f=q('#dynamicRequestForm');if(f)f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const r=await fetch('/api/requests',{method:'POST',headers:apiHeaders(),body:JSON.stringify({recipientId:c.id,type:'brand_to_creator',message:fd.get('message'),amount:fd.get('amount')})});const d=await r.json();if(!r.ok)return toast(d.error||'Request failed');requestData.unshift([c.name,'Sent','Pending']);renderRequests();closeModal();toast('Request sent and saved');};},30);
};
window.sendBrandPitch=async i=>{
 const b=brands[i];if(!apiToken())return authModal('login');
 showModal(`<div class="auth-head"><span class="auth-icon">↗</span><h2>Pitch ${b.name}</h2><p>Explain why you are a strong match.</p></div><form id="dynamicPitchForm"><label>Your pitch</label><textarea name="message" required></textarea><label>Expected fee (INR)</label><input name="amount" type="number" min="0"><button class="btn primary wide">Send Pitch</button></form>`);
 setTimeout(()=>{const f=q('#dynamicPitchForm');if(f)f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const r=await fetch('/api/requests',{method:'POST',headers:apiHeaders(),body:JSON.stringify({recipientId:b.id,type:'creator_to_brand',message:fd.get('message'),amount:fd.get('amount')})});const d=await r.json();if(!r.ok)return toast(d.error||'Pitch failed');requestData.unshift([b.name,'Sent','Pending']);renderRequests();closeModal();toast('Pitch sent and saved');};},30);
};
window.shortlist=async i=>{const c=creators[i];if(apiToken()&&c.id){const r=await fetch(`/api/shortlist/${c.id}`,{method:'POST',headers:apiHeaders()});if(!r.ok){const d=await r.json();return toast(d.error||'Unable to shortlist');}}if(!shortlisted.includes(i))shortlisted.push(i);renderShortlist();renderPayments();toast('Creator shortlisted and saved')};

async function loadDynamicCampaigns(){try{const r=await fetch('/api/campaigns');if(!r.ok)return;const rows=await r.json();if(rows.length){demoCampaigns.splice(0,demoCampaigns.length,...rows.map(c=>({title:c.title,status:c.status.replaceAll('_',' '),budget:`₹${Number(c.budget).toLocaleString('en-IN')}`,apps:0,due:c.deadline||'TBD'})));renderCampaignBoard();}}catch{}}
loadDynamicCampaigns();

window.openProfileEditor=async()=>{
 if(!apiToken())return authModal('login');
 const r=await fetch('/api/profile/me',{headers:apiHeaders()}),d=await r.json();if(!r.ok)return toast(d.error||'Unable to load profile');const p=d.profile||{};
 showModal(`<div class="auth-head"><span class="auth-icon">✎</span><h2>Edit creator profile</h2><p>Changes update discovery results immediately.</p></div><form id="profileEditor"><label>Handle</label><input name="handle" value="${p.handle||''}"><label>Niche</label><input name="niche" value="${p.niche||''}"><label>City</label><input name="city" value="${p.city||''}"><label>Country</label><input name="country" value="${p.country||'India'}"><label>Bio</label><textarea name="bio">${p.bio||''}</textarea><label>Starting price</label><input name="price" type="number" value="${p.price||0}"><label>Profile image URL</label><input name="image" value="${p.image||''}"><label>Cover image URL</label><input name="cover" value="${p.cover||''}"><button class="btn primary wide">Save profile</button></form>`);
 setTimeout(()=>{const f=q('#profileEditor');if(f)f.onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(f));payload.price=Number(payload.price||0);const rr=await fetch('/api/profile/me',{method:'PUT',headers:apiHeaders(),body:JSON.stringify(payload)});const out=await rr.json();if(!rr.ok)return toast(out.error||'Save failed');closeModal();toast('Profile updated dynamically');loadDynamicMarketplace();};},30);
};
window.openBrandEditor=async()=>{
 if(!apiToken())return authModal('login');
 const r=await fetch('/api/profile/me',{headers:apiHeaders()}),d=await r.json();if(!r.ok)return toast(d.error||'Unable to load profile');const p=d.profile||{};
 showModal(`<div class="auth-head"><span class="auth-icon">🏢</span><h2>Edit brand profile</h2><p>Changes update brand search immediately.</p></div><form id="brandEditor"><label>Company name</label><input name="companyName" value="${p.companyName||''}"><label>Industry</label><input name="industry" value="${p.industry||''}"><label>Location</label><input name="location" value="${p.location||''}"><label>Website</label><input name="website" value="${p.website||''}"><label>Description</label><textarea name="description">${p.description||''}</textarea><label>Budget range</label><input name="budgetRange" value="${p.budgetRange||''}"><button class="btn primary wide">Save brand</button></form>`);
 setTimeout(()=>{const f=q('#brandEditor');if(f)f.onsubmit=async e=>{e.preventDefault();const rr=await fetch('/api/profile/me',{method:'PUT',headers:apiHeaders(),body:JSON.stringify(Object.fromEntries(new FormData(f)))});const out=await rr.json();if(!rr.ok)return toast(out.error||'Save failed');closeModal();toast('Brand updated dynamically');loadDynamicMarketplace();};},30);
};
// Add dynamic profile controls to dashboards without changing the existing layout.
setTimeout(()=>{
 const creatorPage=q('#creator-dashboard .dashboard-content')||q('#creator-dashboard .content');if(creatorPage&&!q('#dynamicCreatorEdit'))creatorPage.insertAdjacentHTML('afterbegin','<button id="dynamicCreatorEdit" class="btn primary" onclick="openProfileEditor()">Edit Live Creator Profile</button>');
 const brandPage=q('#dashboard .dashboard-content')||q('#dashboard .content');if(brandPage&&!q('#dynamicBrandEdit'))brandPage.insertAdjacentHTML('afterbegin','<button id="dynamicBrandEdit" class="btn primary" onclick="openBrandEditor()">Edit Live Brand Profile</button>');
},250);
