require('dotenv').config();
const path=require('path');
const crypto=require('crypto');
const express=require('express');
const session=require('express-session');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {read,mutate,id}=require('./lib/db');
const app=express();
const PORT=process.env.PORT||3000;
const BASE_URL=process.env.BASE_URL||`http://localhost:${PORT}`;
const JWT_SECRET=process.env.JWT_SECRET||'replace-this-jwt-secret';
app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:false}));
app.use(rateLimit({windowMs:60_000,limit:180,standardHeaders:true,legacyHeaders:false}));
app.use(session({secret:process.env.SESSION_SECRET||'replace-this-session-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*3600*1000}}));
function safeUser(u){const {passwordHash,...rest}=u;return rest;}
function tokenFor(u){return jwt.sign({sub:u.id,role:u.role},JWT_SECRET,{expiresIn:'7d'});}
function auth(req,res,next){const raw=req.headers.authorization?.replace(/^Bearer\s+/,'')||req.session.token;if(!raw)return res.status(401).json({error:'Authentication required'});try{req.auth=jwt.verify(raw,JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired session'});}}
function role(...roles){return (req,res,next)=>roles.includes(req.auth.role)?next():res.status(403).json({error:'Insufficient permission'});}
function audit(actor,action,target,meta={}){return mutate(db=>db.auditLogs.push({id:id('log'),actor,action,target,meta,createdAt:new Date().toISOString()}));}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'3.0.0',time:new Date().toISOString()}));
app.post('/api/auth/signup',async(req,res)=>{const {name,email,password,role:accountRole='creator'}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});if(!['brand','creator'].includes(accountRole))return res.status(400).json({error:'Invalid role'});const normalized=email.trim().toLowerCase();const db=read();if((db.users||[]).some(u=>u.email===normalized))return res.status(409).json({error:'Email already registered'});const user={id:id('usr'),name:name.trim(),email:normalized,passwordHash:await bcrypt.hash(password,12),role:accountRole,emailVerified:false,status:'active',createdAt:new Date().toISOString()};await mutate(db=>{db.users.push(user);db.notifications.push({id:id('ntf'),userId:user.id,text:'Welcome to CollabAI. Connect your social profiles to complete onboarding.',read:false,createdAt:new Date().toISOString()});});const token=tokenFor(user);req.session.token=token;await audit(user.id,'signup',user.id,{role:accountRole});res.status(201).json({token,user:safeUser(user)});});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;const user=(read().users||[]).find(u=>u.email===String(email||'').toLowerCase());if(!user||!await bcrypt.compare(password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});if(user.status!=='active')return res.status(403).json({error:'Account is not active'});const token=tokenFor(user);req.session.token=token;await audit(user.id,'login',user.id);res.json({token,user:safeUser(user)});});
app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',auth,(req,res)=>{const u=(read().users||[]).find(x=>x.id===req.auth.sub);res.json({user:u?safeUser(u):null});});
app.get('/api/campaigns',(req,res)=>{let rows=read().campaigns||[];const q=String(req.query.q||'').toLowerCase();if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));res.json(rows);});
app.post('/api/campaigns',auth,role('brand'),async(req,res)=>{const c={id:id('cmp'),brandId:req.auth.sub,title:req.body.title,category:req.body.category||'General',budget:Number(req.body.budget||0),status:'draft',deadline:req.body.deadline||null,deliverables:req.body.deliverables||[],createdAt:new Date().toISOString()};await mutate(db=>db.campaigns.push(c));await audit(req.auth.sub,'campaign.create',c.id);res.status(201).json(c);});
app.patch('/api/campaigns/:id/status',auth,role('brand'),async(req,res)=>{let updated;await mutate(db=>{const c=db.campaigns.find(x=>x.id===req.params.id&&x.brandId===req.auth.sub);if(c){c.status=req.body.status;updated=c;}});if(!updated)return res.status(404).json({error:'Campaign not found'});res.json(updated);});
app.post('/api/campaigns/:id/apply',auth,role('creator'),async(req,res)=>{const db=read();const campaign=db.campaigns.find(x=>x.id===req.params.id);if(!campaign)return res.status(404).json({error:'Campaign not found'});if(db.applications.some(x=>x.campaignId===campaign.id&&x.creatorId===req.auth.sub))return res.status(409).json({error:'Already applied'});const a={id:id('app'),campaignId:campaign.id,creatorId:req.auth.sub,pitch:req.body.pitch||'',quote:Number(req.body.quote||0),status:'submitted',createdAt:new Date().toISOString()};await mutate(db=>db.applications.push(a));await audit(req.auth.sub,'campaign.apply',campaign.id);res.status(201).json(a);});
app.get('/api/applications',auth,(req,res)=>{const db=read();res.json((db.applications||[]).filter(a=>req.auth.role==='creator'?a.creatorId===req.auth.sub:(db.campaigns.find(c=>c.id===a.campaignId)?.brandId===req.auth.sub)));});
app.patch('/api/applications/:id',auth,async(req,res)=>{let result;await mutate(db=>{const a=db.applications.find(x=>x.id===req.params.id);if(!a)return;const c=db.campaigns.find(x=>x.id===a.campaignId);if(req.auth.role==='brand'&&c?.brandId===req.auth.sub||req.auth.role==='creator'&&a.creatorId===req.auth.sub){a.status=req.body.status||a.status;result=a;}});if(!result)return res.status(404).json({error:'Application not found'});res.json(result);});
app.post('/api/payments/create',auth,role('brand'),async(req,res)=>{const p={id:id('pay'),brandId:req.auth.sub,creatorId:req.body.creatorId,campaignId:req.body.campaignId||null,amount:Number(req.body.amount||0),currency:req.body.currency||'INR',status:'created',provider:process.env.PAYMENT_PROVIDER||'demo',createdAt:new Date().toISOString()};await mutate(db=>db.payments.push(p));await audit(req.auth.sub,'payment.create',p.id,{amount:p.amount});res.status(201).json({...p,checkoutUrl:`${BASE_URL}/#payments?payment=${p.id}`});});
app.post('/api/payments/:id/confirm-demo',auth,role('brand'),async(req,res)=>{let p;await mutate(db=>{p=db.payments.find(x=>x.id===req.params.id&&x.brandId===req.auth.sub);if(p){p.status='funded';p.fundedAt=new Date().toISOString();}});if(!p)return res.status(404).json({error:'Payment not found'});res.json(p);});
app.get('/api/payments',auth,(req,res)=>res.json((read().payments||[]).filter(p=>req.auth.role==='brand'?p.brandId===req.auth.sub:p.creatorId===req.auth.sub)));
app.post('/api/social/:provider/demo',auth,role('creator'),async(req,res)=>{const provider=req.params.provider;if(!['instagram','tiktok','youtube','facebook'].includes(provider))return res.status(400).json({error:'Unsupported provider'});const account={id:id('soc'),userId:req.auth.sub,provider,username:req.body.username||`demo_${provider}`,displayName:req.body.displayName||'Demo Creator',followers:Number(req.body.followers||50000),engagement:Number(req.body.engagement||5.4),verified:false,source:'demo',lastSyncedAt:new Date().toISOString()};await mutate(db=>{db.socialAccounts=db.socialAccounts.filter(x=>!(x.userId===req.auth.sub&&x.provider===provider));db.socialAccounts.push(account);db.snapshots.push({id:id('snap'),socialAccountId:account.id,userId:req.auth.sub,provider,followers:account.followers,engagement:account.engagement,capturedAt:new Date().toISOString()});});res.status(201).json(account);});
app.get('/api/social/accounts',auth,role('creator'),(req,res)=>res.json((read().socialAccounts||[]).filter(x=>x.userId===req.auth.sub)));
app.get('/api/analytics/creator/:userId',(req,res)=>{const db=read();const accounts=(db.socialAccounts||[]).filter(x=>x.userId===req.params.userId);const snapshots=(db.snapshots||[]).filter(x=>x.userId===req.params.userId);const totalFollowers=accounts.reduce((n,x)=>n+x.followers,0);const avgEngagement=accounts.length?accounts.reduce((n,x)=>n+x.engagement,0)/accounts.length:0;const authenticity=Math.max(35,Math.min(99,Math.round(45+avgEngagement*5+Math.min(20,accounts.length*5))));res.json({totalFollowers,avgEngagement:Number(avgEngagement.toFixed(2)),authenticity,accounts,snapshots});});
app.post('/api/complaints',async(req,res)=>{const row={id:id('cmpnt'),email:req.body.email,type:req.body.type||'General',details:req.body.details,status:'open',createdAt:new Date().toISOString()};await mutate(db=>db.complaints.push(row));res.status(201).json({id:row.id,status:row.status});});
app.post('/api/appeals',async(req,res)=>{const row={id:id('apl'),email:req.body.email,reason:req.body.reason,status:'submitted',createdAt:new Date().toISOString()};await mutate(db=>db.appeals.push(row));res.status(201).json({id:row.id,status:row.status});});
app.get('/api/admin/overview',auth,role('admin'),(req,res)=>{const db=read();res.json({users:db.users.length,campaigns:db.campaigns.length,applications:db.applications.length,payments:db.payments.length,complaints:db.complaints.length,appeals:db.appeals.length,socialAccounts:db.socialAccounts.length});});
// Provider OAuth routes from the previous package remain represented through configuration diagnostics.
app.get('/api/:provider/auth-url',(req,res)=>{const p=req.params.provider.toUpperCase();const client=process.env[`${p}_CLIENT_ID`]||process.env[`${p}_APP_ID`];if(!client)return res.status(503).json({error:`${req.params.provider} credentials are not configured. Use demo import or add credentials in .env.`});res.status(501).json({error:`Real ${req.params.provider} OAuth adapter requires approved app permissions. Configuration placeholders are included in .env.example.`});});
app.get('/api/:provider/profile',(req,res)=>res.status(401).json({error:'Connect the provider first or use demo import'}));
app.post('/api/:provider/disconnect',(req,res)=>res.json({ok:true}));

// ---------- Dynamic marketplace API ----------
function currentUser(req){
  const raw=req.headers.authorization?.replace(/^Bearer\s+/,'')||req.session.token;
  if(!raw)return null;
  try{const claims=jwt.verify(raw,JWT_SECRET);return (read().users||[]).find(u=>u.id===claims.sub)||null;}catch{return null;}
}
function publicCreator(db,u){
  const p=(db.creatorProfiles||[]).find(x=>x.userId===u.id)||{};
  const accounts=(db.socialAccounts||[]).filter(x=>x.userId===u.id);
  const total=accounts.reduce((n,x)=>n+Number(x.followers||0),0)||Number(p.followers||0);
  const eng=accounts.length?accounts.reduce((n,x)=>n+Number(x.engagement||0),0)/accounts.length:Number(p.engagement||0);
  const authScore=Math.max(35,Math.min(99,Math.round(Number(p.authenticity||45+eng*5+Math.min(20,accounts.length*5)))));
  return {id:u.id,name:u.name,handle:p.handle||'@creator',niche:p.niche||'Lifestyle',followers:total,country:p.country||'India',city:p.city||'',engagement:Number(eng.toFixed(2)),avgViews:Number(p.avgViews||0),authenticity:authScore,match:Number(p.match||85),sponsored:Boolean(p.sponsored),price:Number(p.price||0),image:p.image||'',cover:p.cover||'',bio:p.bio||'',email:p.publicEmail||'',phone:p.phone||'',verified:Boolean(p.verified),platforms:accounts.map(a=>a.provider),updatedAt:p.updatedAt||u.createdAt};
}
function publicBrand(db,u){
  const p=(db.brandProfiles||[]).find(x=>x.userId===u.id)||{};
  const campaign=(db.campaigns||[]).find(c=>c.brandId===u.id&&['published','shortlisting','in_progress'].includes(c.status))||(db.campaigns||[]).find(c=>c.brandId===u.id);
  return {id:u.id,name:p.companyName||u.name,industry:p.industry||'General',campaign:campaign?.title||'Open to collaborations',budget:campaign?`₹${Number(campaign.budget||0).toLocaleString('en-IN')}`:(p.budgetRange||'Contact brand'),trust:Number(p.trust||85),match:Number(p.match||85),sponsored:Boolean(p.sponsored),location:p.location||'India',logo:p.logo||String((p.companyName||u.name||'B').split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase(),description:p.description||'',deliverables:(campaign?.deliverables||[]).join(' + ')||'Custom collaboration',verified:Boolean(p.verified),website:p.website||'',updatedAt:p.updatedAt||u.createdAt};
}
app.get('/api/discovery/creators',(req,res)=>{const db=read();let rows=(db.users||[]).filter(u=>u.role==='creator'&&u.status==='active').map(u=>publicCreator(db,u));const q=String(req.query.q||'').toLowerCase();const category=String(req.query.category||'');const minAuth=Number(req.query.minAuth||0);if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(category&&category!=='All Categories')rows=rows.filter(x=>x.niche.toLowerCase().includes(category.toLowerCase()));rows=rows.filter(x=>x.authenticity>=minAuth);rows.sort((a,b)=>(b.sponsored-a.sponsored)||(b.match-a.match)||(b.authenticity-a.authenticity));res.json(rows);});
app.get('/api/discovery/brands',(req,res)=>{const db=read();let rows=(db.users||[]).filter(u=>u.role==='brand'&&u.status==='active').map(u=>publicBrand(db,u));const q=String(req.query.q||'').toLowerCase();const industry=String(req.query.industry||'');if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(industry&&industry!=='All Industries')rows=rows.filter(x=>x.industry===industry);rows.sort((a,b)=>(b.sponsored-a.sponsored)||(b.match-a.match)||(b.trust-a.trust));res.json(rows);});
app.get('/api/profile/me',auth,(req,res)=>{const db=read();const u=db.users.find(x=>x.id===req.auth.sub);const profile=req.auth.role==='creator'?(db.creatorProfiles||[]).find(x=>x.userId===u.id):(db.brandProfiles||[]).find(x=>x.userId===u.id);res.json({user:safeUser(u),profile:profile||{}});});
app.put('/api/profile/me',auth,async(req,res)=>{let result;await mutate(db=>{const key=req.auth.role==='creator'?'creatorProfiles':'brandProfiles';db[key]=db[key]||[];let p=db[key].find(x=>x.userId===req.auth.sub);if(!p){p={id:id(req.auth.role==='creator'?'crp':'brp'),userId:req.auth.sub};db[key].push(p);}const allowed=req.auth.role==='creator'?['handle','niche','country','city','avgViews','price','image','cover','bio','publicEmail','phone','sponsored']:['companyName','industry','location','logo','description','website','budgetRange','sponsored'];for(const k of allowed)if(Object.prototype.hasOwnProperty.call(req.body,k))p[k]=req.body[k];p.updatedAt=new Date().toISOString();result=p;});await audit(req.auth.sub,'profile.update',req.auth.sub);res.json(result);});
app.post('/api/requests',auth,async(req,res)=>{const {recipientId,type='collaboration',message='',campaignId=null,amount=null}=req.body;if(!recipientId||recipientId===req.auth.sub)return res.status(400).json({error:'Valid recipient required'});const db=read();if(!db.users.some(u=>u.id===recipientId))return res.status(404).json({error:'Recipient not found'});const row={id:id('req'),senderId:req.auth.sub,recipientId,type,message,campaignId,amount:amount==null?null:Number(amount),status:'pending',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await mutate(db=>{db.requests=db.requests||[];db.requests.push(row);db.notifications.push({id:id('ntf'),userId:recipientId,text:`New ${type} request received`,read:false,createdAt:new Date().toISOString()});});await audit(req.auth.sub,'request.create',row.id);res.status(201).json(row);});
app.get('/api/requests',auth,(req,res)=>{const db=read();res.json((db.requests||[]).filter(x=>x.senderId===req.auth.sub||x.recipientId===req.auth.sub).map(x=>({...x,sender:db.users.find(u=>u.id===x.senderId)?.name,recipient:db.users.find(u=>u.id===x.recipientId)?.name})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));});
app.patch('/api/requests/:id',auth,async(req,res)=>{let row;await mutate(db=>{row=(db.requests||[]).find(x=>x.id===req.params.id&&(x.senderId===req.auth.sub||x.recipientId===req.auth.sub));if(row){row.status=req.body.status||row.status;row.updatedAt=new Date().toISOString();}});if(!row)return res.status(404).json({error:'Request not found'});res.json(row);});
app.post('/api/shortlist/:creatorId',auth,role('brand'),async(req,res)=>{let row;await mutate(db=>{db.shortlists=db.shortlists||[];row=db.shortlists.find(x=>x.brandId===req.auth.sub&&x.creatorId===req.params.creatorId);if(!row){row={id:id('shl'),brandId:req.auth.sub,creatorId:req.params.creatorId,createdAt:new Date().toISOString()};db.shortlists.push(row);}});res.status(201).json(row);});
app.get('/api/shortlist',auth,role('brand'),(req,res)=>{const db=read();res.json((db.shortlists||[]).filter(x=>x.brandId===req.auth.sub).map(x=>({...x,creator:publicCreator(db,db.users.find(u=>u.id===x.creatorId))})));});
app.post('/api/messages',auth,async(req,res)=>{const {recipientId,body}=req.body;if(!recipientId||!body)return res.status(400).json({error:'Recipient and message required'});const row={id:id('msg'),senderId:req.auth.sub,recipientId,body:String(body).slice(0,4000),read:false,createdAt:new Date().toISOString()};await mutate(db=>{db.messages=db.messages||[];db.messages.push(row);db.notifications.push({id:id('ntf'),userId:recipientId,text:'New message received',read:false,createdAt:new Date().toISOString()});});res.status(201).json(row);});
app.get('/api/messages/:userId',auth,(req,res)=>{const db=read();res.json((db.messages||[]).filter(x=>(x.senderId===req.auth.sub&&x.recipientId===req.params.userId)||(x.recipientId===req.auth.sub&&x.senderId===req.params.userId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));});
app.get('/api/notifications',auth,(req,res)=>res.json((read().notifications||[]).filter(x=>x.userId===req.auth.sub).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.patch('/api/notifications/:id/read',auth,async(req,res)=>{let row;await mutate(db=>{row=db.notifications.find(x=>x.id===req.params.id&&x.userId===req.auth.sub);if(row)row.read=true;});if(!row)return res.status(404).json({error:'Notification not found'});res.json(row);});
app.get('/api/admin/users',auth,role('admin'),(req,res)=>res.json((read().users||[]).map(safeUser)));
app.patch('/api/admin/users/:id',auth,role('admin'),async(req,res)=>{let u;await mutate(db=>{u=db.users.find(x=>x.id===req.params.id);if(u&&req.body.status)u.status=req.body.status;});if(!u)return res.status(404).json({error:'User not found'});res.json(safeUser(u));});


// ---------- Creator deliverables, cart orders and checkout ----------
app.get('/api/creators/:creatorId/services',(req,res)=>{const db=read();res.json((db.creatorServices||[]).filter(x=>x.creatorId===req.params.creatorId&&x.active!==false));});
app.post('/api/creator/services',auth,role('creator'),async(req,res)=>{const {platform,type,title,description,price,deliveryDays=7,revisions=1}=req.body;if(!platform||!type||!title||Number(price)<=0)return res.status(400).json({error:'Platform, type, title and valid price are required'});const row={id:id('svc'),creatorId:req.auth.sub,platform,type,title,description:String(description||'').slice(0,1000),price:Number(price),deliveryDays:Number(deliveryDays),revisions:Number(revisions),active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await mutate(db=>{db.creatorServices=db.creatorServices||[];db.creatorServices.push(row)});await audit(req.auth.sub,'service.create',row.id);res.status(201).json(row);});
app.patch('/api/creator/services/:id',auth,role('creator'),async(req,res)=>{let row;await mutate(db=>{row=(db.creatorServices||[]).find(x=>x.id===req.params.id&&x.creatorId===req.auth.sub);if(row){for(const k of ['platform','type','title','description','price','deliveryDays','revisions','active'])if(Object.hasOwn(req.body,k))row[k]=req.body[k];row.updatedAt=new Date().toISOString();}});if(!row)return res.status(404).json({error:'Service not found'});res.json(row);});
app.delete('/api/creator/services/:id',auth,role('creator'),async(req,res)=>{let removed=false;await mutate(db=>{const before=(db.creatorServices||[]).length;db.creatorServices=(db.creatorServices||[]).filter(x=>!(x.id===req.params.id&&x.creatorId===req.auth.sub));removed=db.creatorServices.length<before;});if(!removed)return res.status(404).json({error:'Service not found'});res.json({ok:true});});
app.post('/api/orders',auth,role('brand'),async(req,res)=>{const db=read(),items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:'Cart is empty'});const normalized=[];for(const item of items){const svc=(db.creatorServices||[]).find(x=>x.id===item.serviceId&&x.active!==false);if(!svc)return res.status(400).json({error:`Service ${item.serviceId} is unavailable`});const quantity=Math.max(1,Math.min(20,Number(item.quantity||1)));normalized.push({serviceId:svc.id,creatorId:svc.creatorId,platform:svc.platform,type:svc.type,title:svc.title,unitPrice:svc.price,quantity,lineTotal:svc.price*quantity});}const subtotal=normalized.reduce((n,x)=>n+x.lineTotal,0),platformFee=Math.round(subtotal*.05),tax=Math.round(platformFee*.18),total=subtotal+platformFee+tax;const order={id:id('ord'),brandId:req.auth.sub,items:normalized,brief:String(req.body.brief||'').slice(0,3000),deadline:req.body.deadline||null,usageRights:req.body.usageRights||'organic',subtotal,platformFee,tax,total,currency:'INR',status:'awaiting_payment',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await mutate(db=>{db.orders=db.orders||[];db.orders.push(order);for(const creatorId of new Set(normalized.map(x=>x.creatorId)))db.notifications.push({id:id('ntf'),userId:creatorId,text:`New order ${order.id} is awaiting payment`,read:false,createdAt:new Date().toISOString()});});await audit(req.auth.sub,'order.create',order.id,{total});res.status(201).json(order);});
app.get('/api/orders',auth,(req,res)=>{const rows=(read().orders||[]).filter(o=>req.auth.role==='brand'?o.brandId===req.auth.sub:o.items.some(i=>i.creatorId===req.auth.sub));res.json(rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));});
app.post('/api/orders/:id/checkout-demo',auth,role('brand'),async(req,res)=>{let order,payment;await mutate(db=>{order=(db.orders||[]).find(x=>x.id===req.params.id&&x.brandId===req.auth.sub);if(order&&order.status==='awaiting_payment'){order.status='paid';order.paidAt=new Date().toISOString();order.updatedAt=order.paidAt;payment={id:id('pay'),brandId:req.auth.sub,orderId:order.id,creatorIds:[...new Set(order.items.map(i=>i.creatorId))],amount:order.total,currency:order.currency,status:'funded',provider:'demo',createdAt:new Date().toISOString(),fundedAt:new Date().toISOString()};db.payments.push(payment);}});if(!order)return res.status(404).json({error:'Order not found'});if(!payment)return res.status(409).json({error:'Order is not awaiting payment'});res.json({order,payment});});

app.use(express.static(path.join(__dirname)));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.listen(PORT,()=>console.log(`CollabAI running at ${BASE_URL}`));
